### PR TITLE
XML to dict symetric conversion

### PR DESCRIPTION
**Pull request by pierreroth64**
One would expect that converting XML to dict and converting this dict back to XML restores the initial XML file. Extra <#value>...</#value> are inserted.

This pull request adds a test case that reproduces the issue.

### CODE REVIEW

**Comment by pierreroth64** [comment]
Added little fix and updated the text case to remove the extra <#value> tags from output (cca556d)

**Comment by pierreroth64** [comment]
Ok, seems that the pull request is now done from my point of view. If any needed change, please ask. Hope that you'll be interested in this little fix.

**Comment by pierreroth64** [comment]
Hi,
Is there any chance this pull request to be merged into mainline?
Thanks a lot for your feedback.

**Comment by rahulkmr** [comment]
Hi @pierreroth64 . Sorry about the delay. I will review and merge it today.

**Pull request merged**
